name: test
on:
  - workflow_call

permissions:
  contents: read

jobs:
  test_linux:
    runs-on: ubuntu-latest
    env:
      REDIS_HOST: 127.0.0.1
      REDIS_PORT: 7007
      REDIS_CLUSTER_PORTS: '7000,7001,7002'
    strategy:
      matrix:
        node-version: ['latest']
        redis-version: ['6.0.20', '7.0.0']

    services:
      redis:
        image: grokzen/redis-cluster:${{ matrix.redis-version }}
        env:
          REDIS_CLUSTER_IP: 0.0.0.0
          IP: 0.0.0.0
          STANDALONE: 'true'
        ports:
          - '7007:7007'
          - '7000-7005:7000-7005'

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test
